name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKERHUB_TOKEN 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cwongsgp/node-test:$(date +%s)
      
    - name: Docker Push
      run: docker push cwongsgp/node-test
    
